# SPDX-FileCopyrightText: Copyright (c) 2025 Orange
# SPDX-License-Identifier: Mozilla Public License 2.0
#
# This software is distributed under the MPL-2.0 license.
# the text of which is available at https://www.mozilla.org/en-US/MPL/2.0/
# or see the "LICENSE" file for more details.

formatter: "markdown table" # this is requiredversion: "0.16"
header-from: main.tf
footer-from: ""
recursive:
  enabled: false
  path: ""
  
sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}  
  
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  
output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
      
output-values:
  enabled: false
  from: ""
  
sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true