# SPDX-FileCopyrightText: Copyright (c) 2025 Orange
# SPDX-License-Identifier: Mozilla Public License 2.0
#
# This software is distributed under the MPL-2.0 license.
# the text of which is available at https://www.mozilla.org/en-US/MPL/2.0/
# or see the "LICENSE" file for more details.

# --------------------------------------------------------------
# WARNING: This file is managed by centralized sync management system.
# Do not edit this file directly, your changes will be overwritten.
# See https://github.com/orange-cloudavenue/workflows for more information.
# --------------------------------------------------------------
plugin "terraform" {
  enabled = true
  preset  = "recommended"
}